### ISSUE TITLE
Bold Fonts

### ISSUE THREAD

**Issue by mapsonx** [jscher2000/switch-to-previous-active-tab#1]
Excellent addon.  Best of it's kind, IMO.

Would it be possible to have bold fonts as an option for the previous sites list?

thanks

**Comment by jscher2000** [comment]
Would the bold signify anything, or is the font I'm using just too light on your display so you would like all of the text bold?

**Comment by nollinvoyd** [comment]
The background color scheme works.  The font itself is fine.  "Too light"?  Maybe.  For me, it's a bit "skinny" and being white, a little hard on the eyes.  If I had a choice, I'd probably opt for black text.  

In general, I pretty much prefer bold interface fonts.  I think your list would be well complimented by the bold font, white or black.  

We probably spend way too much time staring at a computer screen, so anything I can do to reduce the eyestrain is good with me.

Maybe you could add a light and dark scheme options?

**Comment by jscher2000** [comment]
You can try the new options in version 1.4. For example, try switching from the standard UI font to your sans-serif font, which may be "heavier." You also can bold whatever font you use, and/or increase the size.

**Comment by nollinvoyd** [comment]
Perfect.  Really makes a big difference for me.

Just curious about the difference between "Window" and "Global".  I only have one window, but there are more entries in Global than Windows.

**Comment by jscher2000** [comment]
> Just curious about the difference between "Window" and "Global". I only have one window, but there are more entries in Global than Windows.

By default, the dialog shows the (up to) 15 most recent tabs for the current window and the (up to) 30 recent tabs across all windows (global). It's certainly possible that the older tabs from the same window make up the rest of the global list; I don't try to filter them out. I hadn't thought of or noticed that possibility because I seldom have fewer than 6 windows open.

**Comment by jscher2000** [comment]
I think I'm going to declare victory on this issue.
