### ISSUE TITLE
Does not work correctly under certain circumstances

### ISSUE THREAD

**Issue by sakkamade** [jscher2000/switch-to-previous-active-tab#10]
This is awfully specific issue, so I'll try to walk you through it step by step. 

#### Steps to reproduce

Conditions:
1. Firefox is closed
2. I click the link in external application which calls Firefox to open it

So, when I do that with version 1.9.6, it is like so:

3. New tab with that link opens at the very end
2. Calling the action "Switch to previous active tab" by assigned shortcut would switch browser to the tab that I closed it with

#### Problem

However, with version 2.0 and 2.0.1 at the step 4 I am being guided to the pinned tab.

#### Other information

OS: Arch Linux

**Comment by sakkamade** [comment]
> However, with version 2.0 and 2.0.1 at the step 4 I am being guided to the pinned tab.

And if I don't have pinned tabs, the shortcut does nothing at all.

**Comment by jscher2000** [comment]
Hi, I suspect this is because of the new setting to skip unloaded tabs. Because Firefox launched from an external link, the last tab was not loaded (it is still pending/discarded). However, pinned tabs are always loaded. 

Try unchecking the box for this feature (second one):

![Options](https://addons.cdn.mozilla.net/user-media/previews/full/261/261404.png)

**Comment by sakkamade** [comment]
Hello. 

Whoa! Never knew this add-on had settings! Hahahaha. 

(Have been using it for several years...)

**Comment by sakkamade** [comment]
> Try unchecking the box for this feature (second one):

Unchecking "Button/key skips unloaded tabs" didn't help.

**Comment by jscher2000** [comment]
You can tell I'm not a professional developer... I missed the fact that user preferences take time to retrieve, so the lists were being built too early based on default settings. I think I've fixed it in version 2.0.2.

**Comment by sakkamade** [comment]
> I think I've fixed it in version 2.0.2.

Yes, it is fixed. Thank you very much! :heart: 

 ---

Perhaps settings window can be added somewhere else as well, so to be accessible from `about:addons` page too? 
1. As the entry of add-on's three-dot menu which will open a "New tab" with settings? ([GlitterDrag](https://github.com/harytfw/GlitterDrag) does that.)
2. Directly as a tab of the add-on page—between "Details" and "Permissions"?

Should I open a separate issue about it?

**Comment by jscher2000** [comment]
There isn't any perfect way to do Options as far as I'm concerned...  You can open a separate issue.
