### ISSUE TITLE
Ability to access settings from `about:addons` page

### ISSUE THREAD

**Issue by sakkamade** [jscher2000/switch-to-previous-active-tab#11]
After using this amazing extension for several years I was able to access settings only now.
That is since the only way to open it right now is to click right mouse button on the toolbar icon, and I have been simply removing it so far.

So, perhaps settings window can be added somewhere else as well, so to be accessible from `about:addons` page too?

**Comment by jscher2000** [comment]
I uploaded version 2.2, which includes a button on the Add-ons page to launch the options panel in a floating window.

**Comment by sakkamade** [comment]
Looks good to me. I'd consider it fixed.
Thank you!
