### ISSUE TITLE
Keyboard navigation in list

### ISSUE THREAD

**Issue by Dim-Tim-1963** [jscher2000/switch-to-previous-active-tab#13]
Is it possible to 1) Add a keyboard shortcut to open popup with _list_?  2) Allow keyboard navigation in list (at least down, up, enter to select, esc to close)?  I got used to _tab groups_ addon, and now _Ctrl-Tab_ is limited to active group.  With keyboard navigation enabled, your addon would be a gread alternative to Ctrl-Tab. :)

**Comment by jscher2000** [comment]
For (1), yes, that's easy. I'm going to upload a version 2.3 now with this feature.

For (2), Esc should close it already, but the other scripts will take some time to write and test.

**Comment by Dim-Tim-1963** [comment]
Thanks! :)

**Comment by jscher2000** [comment]
Version 2.4 has my initial design for keyboard support:

* Ctrl+Shift+Down Arrow opens the list
* You can use the Left and Right arrow keys to switch between the current window list and the global list
* You can use the Up and Down arrow keys to select a tab to switch to, then press Enter to switch

I tested in a very simplified scenario (no container tabs or hidden tabs) since it was getting late. Let me know how it goes.

**Comment by Dim-Tim-1963** [comment]
Great! I don't use container tabs, but with Tab Groups works flawlessly.  Perhaps one more thing to add: close popup on ENTER (maybe optionally).

**Comment by jscher2000** [comment]
I noticed that the list doesn't scroll automatically when I arrow down, so I'll open a new issue for that.

Regarding the list staying open, you could switch over to the Options tab to see whether the box to keep it open is checked:

![List-stays-open](https://user-images.githubusercontent.com/8264646/192152092-705f4052-8889-424c-9538-570c1d218c14.png)

**Comment by Dim-Tim-1963** [comment]
Yes, unchecking that option helps.  But when it's checked, and I press Enter to select a tab, the tab gets focus, but now only ESC works, and Up, Down and Enter are ignored.

**Comment by jscher2000** [comment]
Yes, Firefox moves the focus into the page in the tab that was activated, so your arrows go there instead. 

There probably is a way to move the focus back to the popup after the tab settles -- from the popup. I'd rather not inject scripts into pages to do that if it can be avoided. Do you want to open a new issue for that?

**Comment by Dim-Tim-1963** [comment]
After the page is activated, arrow keystrokes go nowhere: Up and Down should scroll the page, but they don't.  But I found out that pressing TAB "unfreezes"  the list, and Up/Down/Enter act as they should again.  Maybe it's a clue.  And personally I am good with closing popup after pressing Enter. :)
