### ISSUE TITLE
Add middle-click mouse handler

### ISSUE THREAD

**Issue by mystiquewolf** [jscher2000/switch-to-previous-active-tab#15]
Feature request: Add handler for middle-click with touchpad/mouse.

If main left click is set to show popup list, middle click will switch to the last previous used tab. Else if main left click is set to switch to previous used tab, middle click will show the popup list instead.

[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/onClicked#addlistener_syntax](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/onClicked#addlistener_syntax)

**Comment by jscher2000** [comment]
Thank you for the suggestion. I've added this in version 2.5 tonight.

**Comment by jscher2000** [comment]
I assume this is working for you now but, if not, let me know.
