### ISSUE TITLE
Doesn't save that I don't want reload tabs in menu

### ISSUE THREAD

**Issue by RikisX** [jscher2000/switch-to-previous-active-tab#2]
If I set "no thanks", so I don't see reload tabs menu on tab, it works until I restart firefox. And then it is showing again, even if it's turned off in settings.

**Comment by jscher2000** [comment]
Hmm, I see what you mean. When I check the preferences, it shows the current preference is "No thanks", so the change was stored, but somehow the menu item was generated anyway. I don't yet understand what is causing it, but I'll see what I can do.

**Comment by jscher2000** [comment]
Sorry for the delay, I figured out where the problem was and it is fixed in version 1.7.
