### ISSUE TITLE
Random send order with new 'activate tab' option

### ISSUE THREAD

**Issue by Indigian** [jscher2000/switch-to-previous-active-tab#4]
Many thanks for getting this to work in the first place.
I don't know if this is an 'issue' or changable aspect but.............

Is it possible to have option of sending tabs numerically or such,essentially in a given order?
Extension does work brilliantly apart from this random send order.

Tried my send order right to left and left to right
Once right clicked and reloaded all tabs,enter enter ........
Reloaded tabs are perfect except not in the order I sent in offline mode

Thanks

**Comment by jscher2000** [comment]
Reload All Tabs uses the same kind of order as the lists of recently used tabs: most recent to oldest. 

https://github.com/jscher2000/switch-to-previous-active-tab/blob/master/background.js#L640

That could be modified if you have a special need to reload them in the original order loaded. If I could figure out how to determine that.

**Comment by Indigian** [comment]
> 
> 
> Reload All Tabs uses the same kind of order as the lists of recently used tabs: most recent to oldest.
> 
> https://github.com/jscher2000/switch-to-previous-active-tab/blob/master/background.js#L640
> 
> That could be modified if you have a special need to reload them in the original order loaded. If I could figure out how to determine that.

I need them to reload and send in the order I 'sent' them when offline.
This doesn't seem to follow 'most recently used' tab order or maybe it's a tad behind in timings?

Here's how I go about it.
1 tab open,configure it
add tab,configure
add tab,configure
add tab,configure
click back through the tabs,4th is active
so click tab 3
click tab 2
click tab 1
go offline
send tab 1
send 2
send 3
send 4
go online
click back through the tabs
3
2
1
tab 1 is now active
right click tab,reload all
enter,enter,enter,enter

FF56 sends the tabs in order 1,2,3,4
I have actions in the tab that need to be done in order.

Not sure which 'recent' tab list the ext is reading but it 'sends' in the wrong order.

**Comment by jscher2000** [comment]
In your example, the order should be:

Switch to 2 because it needs attention, Enter on 2, Reload 2
Switch to 3 because it needs attention, Enter on 3, Reload 3
Switch to 4 because it needs attention, Enter on 4, Reload 4
Return to 1 (current tab is returned to last), Enter on 1, Reload 1

However, I haven't tested the offline scenario.

**Comment by Indigian** [comment]
> 
> 
> In your example, the order should be:
> 
> Switch to 2 because it needs attention, Enter on 2, Reload 2
> Switch to 3 because it needs attention, Enter on 3, Reload 3
> Switch to 4 because it needs attention, Enter on 4, Reload 4
> Return to 1 (current tab is returned to last), Enter on 1, Reload 1
> 
> However, I haven't tested the offline scenario.

In both examples I tried,RtoL & LtoR the 1st tab I send offline which is the same tab I make active to reload all from did seem to end up last both times.
If tabs can be sent in 'made' order that's cool,1,2,3,4....etc

The tab doesn't really need reloading after the 'enter' command tbf

Basically the tab is a command with a confirmation box,you fill in your entries,press enter,box pops up 'are you sure',enter again to confirm.
Sometimes 4 commands are needed,the closer together they are the better.
Each tab you 'send' but don't confirm.
So when I go offline I 'confirm' the tabs in the order I want sent.
Go back online,click on the tab to bring it to the front,reversed order so tab4,3,2 then 1.
Right click tab1,reload all,enter,enter,enter and enter.

**Comment by jscher2000** [comment]
The reason the tab displayed when you clicked Reload All Tabs is always last is how the extension finds the tabs that need attention: Firefox only marks _background_ tabs with the attention flag/blue dot. After cycling through those, then the extension returns to the tab that was displayed at the time you clicked Reload All Tabs.

**Comment by Indigian** [comment]
> 
> 
> The reason the tab displayed when you clicked Reload All Tabs is always last is how the extension finds the tabs that need attention: Firefox only marks _background_ tabs with the attention flag/blue dot. After cycling through those, then the extension returns to the tab that was displayed at the time you clicked Reload All Tabs.

Ok cool
I can work around that just use the tab for reload all that I want sent last.
Experiments are the order of the day,if it always sends 2,3,4 then 1 brilliant,I'll just organise the tab actions/instructions accordingly.

Thanks
