### ISSUE TITLE
Ignore tabs view with Panorama Tab Groups extension, or similar ones

### ISSUE THREAD

**Issue by Wronschien** [jscher2000/switch-to-previous-active-tab#5]
Hello, using Panorama Tab Groups, I find it a bit awkward that switching to previous tab gets me to the tabs viewer as it's technically the previous one, but actually I was hoping for the real previous content one. Maybe I'm not clear if you don't know how Panorama extension works, tell me then.

So, ignoring the "tabs viewer" tab would be very nice. Its title is "Panorama View", that should be enough to discriminate, I suppose. I can't see any other way actually.

**Comment by jscher2000** [comment]
It's a good idea to let the user designate URLs or tab titles to skip over when doing the quick switch (i.e., it would still be in the list, but would be ignored by the one-click/keyboard shortcut action). This could be added as a button context menu option. Creating a UI to manage a list is more work, so I'm trying to think of a way to release it quickly and safely.

**Comment by Wronschien** [comment]
Great news, thank you

**Comment by jscher2000** [comment]
I posted a version 1.9.5 that should work for this. The title "Panorama View" is hard-coded for now. Please let me know if you discover any problems.

**Comment by Wronschien** [comment]
Well that was quick ! after a couple minutes of testing everything seems alright, thank you.
