### ISSUE TITLE
Add option to auto-hide the tablist popup on click of recent tab

### ISSUE THREAD

**Issue by mystiquewolf** [jscher2000/switch-to-previous-active-tab#6]
Currently 3 clicks are needed, one to show the list, one to switch to some tab, and one outside of tablist to hide the tablist. I suggest to make the tablist automatically hide when you select the tab by clicking on it in the list.

**Comment by jscher2000** [comment]
There is a setting for that. When you're viewing the list drop-down, switch to the Options panel and on the right side, uncheck "Keep open in same window". Then click Save Settings.

Does that work on yours?

**Comment by mystiquewolf** [comment]
Oh, yes, this seems to work perfectly! I'm sorry for bothering you. Maybe it should be names "Auto-hide tablist on tab selection" or "Keep tablist open after tab switch".

Thank you for this amazing wonderful useful addon.
